### ISSUE TITLE
Configure to run as a webapp (Chrome)

### ISSUE THREAD

**Issue by federicocesena** [dit-mt-unibo/menudelgiorno#1]
Technically it should work, I did 'flutter create .' and I can choose Chrome/Edge/Desktop when I do 'flutter run'.
But UI breaks at login:

Error: UnimplementedError: androidInfo() has not been implemented.
    at Object.throw_ [as throw] (http://localhost:54321/dart_sdk.js:5080:11)
    at device_info_plus_web.DeviceInfoPlusPlugin.new.androidInfo
    (http://localhost:54321/packages/device_info_plus_platform_interface/method_channel/method_channel_device_info.dart.
    lib.js:65:17)
    at device_info_plus.DeviceInfoPlugin.new.androidInfo
    (http://localhost:54321/packages/device_info_plus/device_info_plus.dart.lib.js:39:113)
    at androidInfo.next (<anonymous>)
    at runBody (http://localhost:54321/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:54321/dart_sdk.js:40691:7)
    at get androidInfo [as androidInfo]
    (http://localhost:54321/packages/device_info_plus/device_info_plus.dart.lib.js:36:20)
    at login.LoginScreen.new._doLogin
    (http://localhost:54321/packages/menudelgiorno/screen/app/registrazione.dart.lib.js:5373:45)
    at _doLogin.next (<anonymous>)
    at runBody (http://localhost:54321/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:54321/dart_sdk.js:40691:7)
    at [_doLogin] (http://localhost:54321/packages/menudelgiorno/screen/app/registrazione.dart.lib.js:5370:20)
    at login.LoginScreen.new.<anonymous>
    (http://localhost:54321/packages/menudelgiorno/screen/app/registrazione.dart.lib.js:5390:75)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:54321/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:54321/dart_sdk.js:40691:7)
    at http://localhost:54321/packages/menudelgiorno/screen/app/registrazione.dart.lib.js:5389:583
    at [_handleTap] (http://localhost:54321/packages/flutter/src/material/icon_button.dart.lib.js:42247:31)
    at tap.TapGestureRecognizer.new.invokeCallback
    (http://localhost:54321/packages/flutter/src/gestures/recognizer.dart.lib.js:198:18)
    at tap.TapGestureRecognizer.new.handleTapUp
    (http://localhost:54321/packages/flutter/src/gestures/tap.dart.lib.js:411:42)
    at [_checkUp] (http://localhost:54321/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer
    (http://localhost:54321/packages/flutter/src/gestures/tap.dart.lib.js:166:23)
    at tap.TapGestureRecognizer.new.handleEvent
    (http://localhost:54321/packages/flutter/src/gestures/recognizer.dart.lib.js:444:16)
    at [_dispatch] (http://localhost:54321/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
    at http://localhost:54321/packages/flutter/src/gestures/pointer_router.dart.lib.js:112:26
    at LinkedMap.new.forEach (http://localhost:54321/dart_sdk.js:27745:11)
    at [_dispatchEventToRoutes] (http://localhost:54321/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:29)
    at pointer_router.PointerRouter.new.route
    (http://localhost:54321/packages/flutter/src/gestures/pointer_router.dart.lib.js:105:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent
    (http://localhost:54321/packages/flutter/src/gestures/binding.dart.lib.js:367:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:54321/packages/flutter/src/gestures/binding.dart.lib.js:355:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:54321/packages/flutter/src/rendering/layer.dart.lib.js:5440:13)
    at [_handlePointerEventImmediately]
    (http://localhost:54321/packages/flutter/src/gestures/binding.dart.lib.js:331:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:54321/packages/flutter/src/gestures/binding.dart.lib.js:305:43)
    at [_flushPointerEventQueue] (http://localhost:54321/packages/flutter/src/gestures/binding.dart.lib.js:295:14)
    at [_handlePointerDataPacket] (http://localhost:54321/packages/flutter/src/gestures/binding.dart.lib.js:286:54)
    at Object.invoke1 (http://localhost:54321/dart_sdk.js:191747:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:54321/dart_sdk.js:171943:15)
    at [_onPointerData] (http://localhost:54321/dart_sdk.js:172879:49)
    at http://localhost:54321/dart_sdk.js:173317:28
    at http://localhost:54321/dart_sdk.js:173273:16
    at loggedHandler (http://localhost:54321/dart_sdk.js:172978:11)

**Comment by federicocesena** [comment]
Fixed in change https://github.com/dit-mt-unibo/menudelgiorno/commit/9d6bffd25e16b7c27e5ef852b673c73da6391890 by using https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html
